server:
  port: 8085 # Optional: Sets the application's port
spring:
  application:
    name: EmployeeManagement
  datasource:
    url: jdbc:mysql://localhost:3306/employee_management_system
    username: root
    password: tiger
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      # Options: none, update, create, create-drop, validate
      ddl-auto: update
    # Optional: Shows the generated SQL in the console
    show-sql: true
    properties:
      hibernate:
        # Specifies the MySQL dialect for Hibernate
        dialect: org.hibernate.dialect.MySQLDialect
